language: node_js
node_js:
  - 11
cache:
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
script:
  - yarn test
after_success:
  - yarn codecov
branches:
  only:
    - master
